package tables;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.misc.BaseDaoEnabled;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "Addresses")
public class Address extends BaseDaoEnabled<Address, Integer> {
	
	@DatabaseField(generatedId = true, columnName = "id", canBeNull = false)
	private int id;
	
	@DatabaseField(columnName = "street_address", canBeNull = false)
	private String streetAddress;
	
	@DatabaseField(columnName = "city", canBeNull = false)
	private String city;
	
	@DatabaseField(columnName = "state", canBeNull = false)
	private String state;
	
	@DatabaseField(columnName = "zip_code", canBeNull = false)
	private String zipCode;
	
	// these two are used to store the accounts and cards for the address
	// 	they are NOT database columns, they are just used to store 
	//	the objects to make life easier
	@ForeignCollectionField(eager = true, orderColumnName = "nickname")
	private ForeignCollection<CreditCard> creditCards;
	
	@ForeignCollectionField(eager = true, orderColumnName = "nickname")
	private ForeignCollection<DebitCard> debitCards;
	
	public Address() {}
	
	public Address(String streetAddress, String city, String state, String zipCode) {
		this.streetAddress = streetAddress;
		this.city = city;
		this.state = state;
		this.zipCode = zipCode;
	}
	
	// no setter for id because it is autogenerated and shouldn't be changed
	// 	once made and put into database
	public int getId() {
		return id;
	}

	public String getStreetAddress() {
		return streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public ForeignCollection<CreditCard> getCreditCards() {
		return creditCards;
	}

	public ForeignCollection<DebitCard> getDebitCards() {
		return debitCards;
	}


}
